/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Mahasiswa_controller;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Andi
 */
public class MahasiswaView extends javax.swing.JFrame {

    /**
     * Creates new form MahasiswaView
     */
    Mahasiswa_controller controller;
    public MahasiswaView() {
        initComponents();
        controller = new Mahasiswa_controller(this);
        controller.clear();
        controller.isiTable();
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JComboBox<String> getCbJurusan() {
        return cbJurusan;
    }

    public JComboBox<String> getCbProdi() {
        return cbProdi;
    }

    public JRadioButton getRbPria() {
        return rbPria;
    }

    public JRadioButton getRbWanita() {
        return rbWanita;
    }

    public JSpinner getSpinTanggal1() {
        return spinTanggal1;
    }

    public JTable getTbMahasiswa() {
        return tbMahasiswa;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtNoBP() {
        return txtNoBP;
    }

    public JTextField getTxtTelepon() {
        return txtTelepon;
    }

    public JTextField getTxtTempatLahir() {
        return txtTempatLahir;
    }

    public JSpinner getSpinBulan() {
        return SpinBulan;
    }

    public JSpinner getSpinTahun() {
        return SpinTahun;
    }

    public JTextArea getTxtAreaAlamat() {
        return txtAreaAlamat;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Judul = new javax.swing.JLabel();
        lbNoBP = new javax.swing.JLabel();
        txtNoBP = new javax.swing.JTextField();
        lbNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        lbTTL = new javax.swing.JLabel();
        txtTempatLahir = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        spinTanggal1 = new javax.swing.JSpinner();
        SpinBulan = new javax.swing.JSpinner();
        SpinTahun = new javax.swing.JSpinner();
        lbAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAlamat = new javax.swing.JTextArea();
        lbNoTelepon = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        lbJurusan = new javax.swing.JLabel();
        cbJurusan = new javax.swing.JComboBox<>();
        lbProdi = new javax.swing.JLabel();
        cbProdi = new javax.swing.JComboBox<>();
        lbGender = new javax.swing.JLabel();
        rbPria = new javax.swing.JRadioButton();
        rbWanita = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMahasiswa = new javax.swing.JTable();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mahasiswa");
        setBackground(new java.awt.Color(255, 204, 51));

        Judul.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        Judul.setText("Database Mahasiswa");

        lbNoBP.setText("NO. BP");

        lbNama.setText("Nama");

        lbTTL.setText("TTL");

        spinTanggal1.setModel(new javax.swing.SpinnerListModel(new String[] {"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"}));
        spinTanggal1.setToolTipText("Tanggal");
        spinTanggal1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinTanggal1.setName(""); // NOI18N

        SpinBulan.setModel(new javax.swing.SpinnerListModel(new String[] {"Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "Nopember", "Desember"}));
        SpinBulan.setToolTipText("Bulan");
        SpinBulan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SpinBulan.setName(""); // NOI18N

        SpinTahun.setModel(new javax.swing.SpinnerNumberModel(2020, 1975, null, 1));
        SpinTahun.setToolTipText("Tahun");
        SpinTahun.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SpinTahun.setName(""); // NOI18N

        lbAlamat.setText("alamat");

        txtAreaAlamat.setColumns(20);
        txtAreaAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAreaAlamat);

        lbNoTelepon.setText("No. telepon");

        lbJurusan.setText("Jurusan");

        cbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "Akuntansi", "Administrasi Niaga", "Bahasa Inggris", "Teknik Elektro", "Teknologi Informasi", "Teknik Mesin", "Teknik Sipil" }));
        cbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJurusanActionPerformed(evt);
            }
        });

        lbProdi.setText("Prodi");

        cbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--" }));
        cbProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdiActionPerformed(evt);
            }
        });

        lbGender.setText("Gender");

        buttonGroup1.add(rbPria);
        rbPria.setText("laki-laki");

        buttonGroup1.add(rbWanita);
        rbWanita.setText("perempuan");

        tbMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. BP", "Nama", "Tempat Lahir", "Tanggal Lahir", "Gender", "Alamat", "No. Telepon", "Jurusan", "Prodi"
            }
        ));
        tbMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbMahasiswa);
        if (tbMahasiswa.getColumnModel().getColumnCount() > 0) {
            tbMahasiswa.getColumnModel().getColumn(0).setMaxWidth(80);
            tbMahasiswa.getColumnModel().getColumn(3).setMaxWidth(130);
            tbMahasiswa.getColumnModel().getColumn(4).setMaxWidth(80);
            tbMahasiswa.getColumnModel().getColumn(6).setMaxWidth(120);
        }

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbAlamat)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1))
                                .addComponent(Judul)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbNoBP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNoBP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNama)
                                        .addComponent(lbTTL))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbPria)
                                                .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbWanita))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(24, 24, 24)
                                                    .addComponent(spinTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(SpinBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(SpinTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(13, 13, 13))))
                                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(306, 306, 306)
                                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNoTelepon)
                                    .addComponent(lbJurusan)
                                    .addComponent(lbProdi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelepon)
                                    .addComponent(cbJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Insert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Update)
                                .addGap(8, 8, 8)
                                .addComponent(Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cancel)
                                .addGap(63, 63, 63))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNoBP)
                    .addComponent(txtNoBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNoTelepon))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJurusan)
                    .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTTL)
                    .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProdi)
                    .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGender)
                            .addComponent(rbPria)
                            .addComponent(rbWanita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAlamat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Insert)
                            .addComponent(Update)
                            .addComponent(Cancel)
                            .addComponent(Delete))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJurusanActionPerformed
        // TODO add your handling code here:
         int pilih;
        String TI[] = {"D3 Teknik Komputer ","D3 Manajemen Informatika","D4 Rekayasa Perangkat Lunak"};
        String M[] = {"D3 Teknik Mesin", "D3 Teknik Alat Berat", "D4 Teknik Manufaktur"};
        String E[] = {"D3 Teknik Listrik", "D3 Teknik Elektro", "D3 Teknik Telekomunikasi",
            "D4 Teknik Elektro", "D4 Teknik Telekomunikasi"};
        String S[] = {"D3 Teknik Sipil","D4 Perencanaan Irigasi Rawa",
            "D4 Manajemen Rek. Konstruksi", "D4 Perancangan Jalan Jembatan"};
        String AN[] = {"D3 Administrasi Bisnis", "D3 Usaha Perjalanan Wisata"};
        String AK[] = {"D3 Akuntansi", "D4 Akuntansi"};
        String BI[] = {"D3 Bahasa Inggris"};
        pilih = cbJurusan.getSelectedIndex();
        switch (pilih){
            case 0:
            cbProdi.setEnabled(false);
            cbProdi.removeAllItems();
            cbProdi.addItem("--pilih--");
            break;
            case 5:
            cbProdi.setEnabled(true);
            cbProdi.removeAllItems();
             for (String TI1 : TI) {
                 cbProdi.addItem(TI1);
             }
            break;

            case 6:
            cbProdi.setEnabled(true);
            cbProdi.removeAllItems();
             for (String M1 : M) {
                 cbProdi.addItem(M1);
             }
            break;

            case 7:
            cbProdi.setEnabled(true);
            cbProdi.removeAllItems();
             for (String S1 : S) {
                 cbProdi.addItem(S1);
             }
            break;

            case 4:
            cbProdi.setEnabled(true);
            cbProdi.removeAllItems();
             for (String E1 : E) {
                 cbProdi.addItem(E1);
             }
            break;

            case 2:
            cbProdi.setEnabled(true);
            cbProdi.removeAllItems();
             for (String AN1 : AN) {
                 cbProdi.addItem(AN1);
             }
            break;

            case 1:
            cbProdi.setEnabled(true);
            cbProdi.removeAllItems();
             for (String AK1 : AK) {
                 cbProdi.addItem(AK1);
             }
            break;

            case 3:
            cbProdi.setEnabled(true);
            cbProdi.removeAllItems();
             for (String BI1 : BI) {
                 cbProdi.addItem(BI1);
                 cbProdi.disable();
             }
            break;

            default:
            JOptionPane.showMessageDialog(null, "Pilih Prodi");
            break;
        }

    }//GEN-LAST:event_cbJurusanActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
        controller.insert();
        controller.isiTable();
    }//GEN-LAST:event_InsertActionPerformed

    private void tbMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMahasiswaMouseClicked
        // TODO add your handling code here:
        controller.onMouseClickTabelMahasiswa();
    }//GEN-LAST:event_tbMahasiswaMouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        controller.update();
        controller.isiTable();
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.isiTable();
    }//GEN-LAST:event_DeleteActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        controller.clear();
    }//GEN-LAST:event_CancelActionPerformed

    private void cbProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MahasiswaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    private javax.swing.JLabel Judul;
    private javax.swing.JSpinner SpinBulan;
    private javax.swing.JSpinner SpinTahun;
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JComboBox<String> cbProdi;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbJurusan;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbNoBP;
    private javax.swing.JLabel lbNoTelepon;
    private javax.swing.JLabel lbProdi;
    private javax.swing.JLabel lbTTL;
    private javax.swing.JRadioButton rbPria;
    private javax.swing.JRadioButton rbWanita;
    private javax.swing.JSpinner spinTanggal1;
    private javax.swing.JTable tbMahasiswa;
    private javax.swing.JTextArea txtAreaAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoBP;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables
}
