/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Uangkuliah_controller;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Andi
 */
public class UangkuliahView extends javax.swing.JFrame {

    /**
     * Creates new form UangKuliahView
     */
    Uangkuliah_controller controller;
    public UangkuliahView() {
        initComponents();
        controller = new Uangkuliah_controller(this);
        controller.clear();
        controller.isiTable();
        controller.isiTableMahasiswa();
    }

    public JSpinner getSpinSemester() {
        return spinSemester;
    }

    public JTextField getTxtTA() {
        return txtTA;
    }

    public JRadioButton getLevel0() {
        return Level0;
    }

    public JRadioButton getLevel1() {
        return Level1;
    }

    public JRadioButton getLevel2() {
        return Level2;
    }

    public JRadioButton getLevel3() {
        return Level3;
    }

    public JRadioButton getLevel4() {
        return Level4;
    }

    public JRadioButton getLevel5() {
        return Level5;
    }

    public JButton getBtnCari() {
        return btnCari;
    }

    public JComboBox<String> getCbJenisPembayaran() {
        return cbJenisPembayaran;
    }

    public JSpinner getjSpinner2() {
        return spinSemester;
    }

    public ButtonGroup getKelompokUkt() {
        return kelompokUkt;
    }

    public JSpinner getSpinJumlah() {
        return spinJumlah;
    }

    public JTable getTableUkt() {
        return tableUkt;
    }

    public JTable getTblMhs() {
        return tblMhs;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtNoBp() {
        return txtNoBp;
    }

    public JTextField getTxtTahunAjaran() {
        return txtTA;
    }

    public JTextField getTxtNoPembayaran() {
        return txtNoPembayaran;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelompokUkt = new javax.swing.ButtonGroup();
        Judul = new javax.swing.JLabel();
        lbNoBp = new javax.swing.JLabel();
        txtNoBp = new javax.swing.JTextField();
        lbNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        lbJenisPembayaran = new javax.swing.JLabel();
        cbJenisPembayaran = new javax.swing.JComboBox<>();
        lbGolongan = new javax.swing.JLabel();
        Level0 = new javax.swing.JRadioButton();
        Level1 = new javax.swing.JRadioButton();
        Level2 = new javax.swing.JRadioButton();
        Level3 = new javax.swing.JRadioButton();
        Level4 = new javax.swing.JRadioButton();
        Level5 = new javax.swing.JRadioButton();
        lbJumlah = new javax.swing.JLabel();
        spinJumlah = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUkt = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMhs = new javax.swing.JTable();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        lbSemester = new javax.swing.JLabel();
        spinSemester = new javax.swing.JSpinner();
        lbTahunAjaran = new javax.swing.JLabel();
        txtTA = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        txtNoPembayaran = new javax.swing.JTextField();
        lbNoPembayaran = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Judul.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        Judul.setText("Pembayaran Uang Kuliah");

        lbNoBp.setText("No BP");

        txtNoBp.setText("1911082006");

        lbNama.setText("Nama");

        txtNama.setText("Andi Irham Marhamuddin");
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        lbJenisPembayaran.setText("Jenis Pembayaran");

        cbJenisPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "Tunai", "Transfer Bank", "e-Wallet" }));

        lbGolongan.setText("Golongan");

        kelompokUkt.add(Level0);
        Level0.setText("0");
        Level0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Level0MouseClicked(evt);
            }
        });

        kelompokUkt.add(Level1);
        Level1.setText("1");
        Level1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Level1MouseClicked(evt);
            }
        });

        kelompokUkt.add(Level2);
        Level2.setText("2");
        Level2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Level2MouseClicked(evt);
            }
        });

        kelompokUkt.add(Level3);
        Level3.setText("3");
        Level3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Level3MouseClicked(evt);
            }
        });

        kelompokUkt.add(Level4);
        Level4.setText("4");
        Level4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Level4MouseClicked(evt);
            }
        });

        kelompokUkt.add(Level5);
        Level5.setText("5");
        Level5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Level5MouseClicked(evt);
            }
        });

        lbJumlah.setText("Jumlah");

        spinJumlah.setModel(new javax.swing.SpinnerNumberModel(500000L, 0L, null, 1L));

        tableUkt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Pembayaran", "Nama", "Jurusan", "Prodi", "Semester", "Tahun Ajaran", "Golongan", "Jenis Pembayaran", "Jumlah", "Tanggal"
            }
        ));
        tableUkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUktMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUkt);

        tblMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. BP", "Nama", "Jurusan", "Prodi"
            }
        ));
        tblMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMhsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMhs);

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        lbSemester.setText("Semester");

        spinSemester.setModel(new javax.swing.SpinnerNumberModel(0, null, 8, 1));

        lbTahunAjaran.setText("Tahun Ajaran");

        txtTA.setText("2019/2020");

        btnCari.setText("cari");

        lbNoPembayaran.setText("No. Pembayaran");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNama)
                                    .addComponent(Judul)
                                    .addComponent(lbGolongan)
                                    .addComponent(lbJumlah)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbJenisPembayaran))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNoPembayaran)
                                            .addComponent(txtNoPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbNoBp)
                                                .addComponent(txtNoBp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnCari))))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Delete)
                                    .addComponent(Cancel))
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spinJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Level0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Level1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Level2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Level3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Level4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Level5)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSemester)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTahunAjaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Judul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNoBp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNama)
                            .addComponent(Insert))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbJenisPembayaran)
                                    .addComponent(lbNoPembayaran))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbGolongan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Level0)
                                    .addComponent(Level1)
                                    .addComponent(Level2)
                                    .addComponent(Level3)
                                    .addComponent(Level4)
                                    .addComponent(Level5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbJumlah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cancel))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSemester)
                    .addComponent(spinSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTahunAjaran)
                    .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void tableUktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUktMouseClicked
        // TODO add your handling code here:
        controller.tableUktMouseClicked();
    }//GEN-LAST:event_tableUktMouseClicked

    private void tblMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMhsMouseClicked
        // TODO add your handling code here:
        controller.tblMhsMouseClicked();
    }//GEN-LAST:event_tblMhsMouseClicked

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
        controller.insert();
        controller.isiTable();
    }//GEN-LAST:event_InsertActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        controller.update();
        controller.isiTable();
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.isiTable();
    }//GEN-LAST:event_DeleteActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        controller.clear();
    }//GEN-LAST:event_CancelActionPerformed

    private void Level0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Level0MouseClicked
        // TODO add your handling code here:
        spinJumlah.setValue(0);
    }//GEN-LAST:event_Level0MouseClicked

    private void Level1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Level1MouseClicked
        spinJumlah.setValue(500000);
    }//GEN-LAST:event_Level1MouseClicked

    private void Level2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Level2MouseClicked
        // TODO add your handling code here:
        spinJumlah.setValue(1500000);
    }//GEN-LAST:event_Level2MouseClicked

    private void Level3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Level3MouseClicked
        // TODO add your handling code here:
        spinJumlah.setValue(2500000);
    }//GEN-LAST:event_Level3MouseClicked

    private void Level4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Level4MouseClicked
        // TODO add your handling code here:
        spinJumlah.setValue(3000000);
    }//GEN-LAST:event_Level4MouseClicked

    private void Level5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Level5MouseClicked
        // TODO add your handling code here:
        spinJumlah.setValue(5000000);
    }//GEN-LAST:event_Level5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UangkuliahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UangkuliahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UangkuliahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UangkuliahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UangkuliahView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    private javax.swing.JLabel Judul;
    private javax.swing.JRadioButton Level0;
    private javax.swing.JRadioButton Level1;
    private javax.swing.JRadioButton Level2;
    private javax.swing.JRadioButton Level3;
    private javax.swing.JRadioButton Level4;
    private javax.swing.JRadioButton Level5;
    private javax.swing.JButton Update;
    private javax.swing.JButton btnCari;
    private javax.swing.JComboBox<String> cbJenisPembayaran;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup kelompokUkt;
    private javax.swing.JLabel lbGolongan;
    private javax.swing.JLabel lbJenisPembayaran;
    private javax.swing.JLabel lbJumlah;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbNoBp;
    private javax.swing.JLabel lbNoPembayaran;
    private javax.swing.JLabel lbSemester;
    private javax.swing.JLabel lbTahunAjaran;
    private javax.swing.JSpinner spinJumlah;
    private javax.swing.JSpinner spinSemester;
    private javax.swing.JTable tableUkt;
    private javax.swing.JTable tblMhs;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoBp;
    private javax.swing.JTextField txtNoPembayaran;
    private javax.swing.JTextField txtTA;
    // End of variables declaration//GEN-END:variables
}
